# Generated by Django 2.0.2 on 2018-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='6iiV3A4474TBOGWmvR8YabZE6bVu48Sq', max_length=100),
        ),
    ]
