# Generated by Django 2.0.2 on 2018-02-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180213_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.IntegerField(default=1518523227),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='SNfK4Flbpf68kh4nuhJdQ4YGgzV691Ts', max_length=100),
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.IntegerField(verbose_name='Scores of user'),
        ),
    ]
