# Generated by Django 2.0.2 on 2018-02-16 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180213_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'verbose_name': 'Код', 'verbose_name_plural': 'Коди'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'рейтинг', 'verbose_name_plural': 'Очки'},
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавлення коду'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата використання коду'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Використано користувачем'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatars/default.jpeg', upload_to='avatars', verbose_name='Фото профілю'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='NTGtZizbPSnqeBLVVmvX0hthdLheo6eR', max_length=100),
        ),
        migrations.AlterField(
            model_name='results',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата гри'),
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.IntegerField(verbose_name='Набрані очки'),
        ),
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гравець'),
        ),
    ]
