# Generated by Django 2.0.2 on 2018-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180216_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Кількість спроб від цього коду'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='JnKWiy67iyixWrs42kTzFTZsubekhvNT', max_length=100),
        ),
    ]
